# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MYRafV2.ui'
#
# Created: Tue Feb 26 00:51:00 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/MYRaf.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.checkBox = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_2.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_2.addWidget(self.checkBox_2, 0, 1, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_2.addWidget(self.checkBox_3, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(582, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 2)
        self.tabWidget_2 = QtGui.QTabWidget(self.tab)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.listWidget = QtGui.QListWidget(self.tab_7)
        self.listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout_3.addWidget(self.listWidget, 0, 0, 1, 3)
        self.label_26 = QtGui.QLabel(self.tab_7)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_3.addWidget(self.label_26, 1, 0, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.tab_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/list-remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_3.addWidget(self.pushButton_3, 1, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.tab_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/list-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_3.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.tabWidget_2.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.listWidget_2 = QtGui.QListWidget(self.tab_8)
        self.listWidget_2.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.gridLayout_4.addWidget(self.listWidget_2, 0, 0, 1, 3)
        self.label_27 = QtGui.QLabel(self.tab_8)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_4.addWidget(self.label_27, 1, 0, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.tab_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_4.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.tab_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_4.addWidget(self.pushButton_4, 1, 2, 1, 1)
        self.tabWidget_2.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_9)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.listWidget_3 = QtGui.QListWidget(self.tab_9)
        self.listWidget_3.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_3.setObjectName(_fromUtf8("listWidget_3"))
        self.gridLayout_5.addWidget(self.listWidget_3, 0, 0, 1, 3)
        self.label_28 = QtGui.QLabel(self.tab_9)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_5.addWidget(self.label_28, 1, 0, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_5.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setIcon(icon2)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_5.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.tabWidget_2.addTab(self.tab_9, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_10)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.listWidget_4 = QtGui.QListWidget(self.tab_10)
        self.listWidget_4.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_4.setObjectName(_fromUtf8("listWidget_4"))
        self.gridLayout_6.addWidget(self.listWidget_4, 0, 0, 1, 3)
        self.label_29 = QtGui.QLabel(self.tab_10)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_6.addWidget(self.label_29, 1, 0, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.tab_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_6.addWidget(self.pushButton_9, 1, 1, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.tab_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setIcon(icon2)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_6.addWidget(self.pushButton_8, 1, 2, 1, 1)
        self.tabWidget_2.addTab(self.tab_10, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget_2, 1, 0, 1, 5)
        self.progressBar = QtGui.QProgressBar(self.tab)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_2.addWidget(self.progressBar, 2, 0, 1, 4)
        self.pushButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("img/go.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_2.addWidget(self.pushButton, 2, 4, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("img/cali.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon4, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab_3)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_21 = QtGui.QWidget()
        self.tab_21.setObjectName(_fromUtf8("tab_21"))
        self.gridLayout_18 = QtGui.QGridLayout(self.tab_21)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.frame_6 = QtGui.QFrame(self.tab_21)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.graphicsView_6 = QtGui.QGraphicsView(self.frame_6)
        self.graphicsView_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.graphicsView_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.graphicsView_6.setObjectName(_fromUtf8("graphicsView_6"))
        self.gridLayout_9.addWidget(self.graphicsView_6, 0, 0, 1, 7)
        spacerItem1 = QtGui.QSpacerItem(46, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 1, 0, 1, 1)
        self.pushButton_45 = QtGui.QPushButton(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_45.sizePolicy().hasHeightForWidth())
        self.pushButton_45.setSizePolicy(sizePolicy)
        self.pushButton_45.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_45.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("img/rr.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_45.setIcon(icon5)
        self.pushButton_45.setObjectName(_fromUtf8("pushButton_45"))
        self.gridLayout_9.addWidget(self.pushButton_45, 1, 1, 1, 1)
        self.pushButton_46 = QtGui.QPushButton(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_46.sizePolicy().hasHeightForWidth())
        self.pushButton_46.setSizePolicy(sizePolicy)
        self.pushButton_46.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_46.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("img/fh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_46.setIcon(icon6)
        self.pushButton_46.setObjectName(_fromUtf8("pushButton_46"))
        self.gridLayout_9.addWidget(self.pushButton_46, 1, 2, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.frame_6)
        self.lineEdit_7.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(75, 25))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout_9.addWidget(self.lineEdit_7, 1, 3, 1, 1)
        self.pushButton_47 = QtGui.QPushButton(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_47.sizePolicy().hasHeightForWidth())
        self.pushButton_47.setSizePolicy(sizePolicy)
        self.pushButton_47.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_47.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("img/fv.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_47.setIcon(icon7)
        self.pushButton_47.setObjectName(_fromUtf8("pushButton_47"))
        self.gridLayout_9.addWidget(self.pushButton_47, 1, 4, 1, 1)
        self.pushButton_48 = QtGui.QPushButton(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_48.sizePolicy().hasHeightForWidth())
        self.pushButton_48.setSizePolicy(sizePolicy)
        self.pushButton_48.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_48.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("img/r.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_48.setIcon(icon8)
        self.pushButton_48.setObjectName(_fromUtf8("pushButton_48"))
        self.gridLayout_9.addWidget(self.pushButton_48, 1, 5, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(46, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 1, 6, 1, 1)
        self.gridLayout_18.addWidget(self.frame_6, 0, 0, 6, 1)
        self.line_5 = QtGui.QFrame(self.tab_21)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_18.addWidget(self.line_5, 0, 1, 6, 1)
        self.label_2 = QtGui.QLabel(self.tab_21)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_18.addWidget(self.label_2, 0, 2, 1, 2)
        self.listWidget_13 = QtGui.QListWidget(self.tab_21)
        self.listWidget_13.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_13.setObjectName(_fromUtf8("listWidget_13"))
        self.gridLayout_18.addWidget(self.listWidget_13, 1, 2, 1, 4)
        self.pushButton_50 = QtGui.QPushButton(self.tab_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_50.sizePolicy().hasHeightForWidth())
        self.pushButton_50.setSizePolicy(sizePolicy)
        self.pushButton_50.setIcon(icon1)
        self.pushButton_50.setObjectName(_fromUtf8("pushButton_50"))
        self.gridLayout_18.addWidget(self.pushButton_50, 2, 4, 1, 1)
        self.pushButton_49 = QtGui.QPushButton(self.tab_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_49.sizePolicy().hasHeightForWidth())
        self.pushButton_49.setSizePolicy(sizePolicy)
        self.pushButton_49.setIcon(icon2)
        self.pushButton_49.setObjectName(_fromUtf8("pushButton_49"))
        self.gridLayout_18.addWidget(self.pushButton_49, 2, 5, 1, 1)
        self.line_6 = QtGui.QFrame(self.tab_21)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_18.addWidget(self.line_6, 3, 2, 1, 4)
        self.label_6 = QtGui.QLabel(self.tab_21)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_18.addWidget(self.label_6, 4, 3, 1, 1)
        self.comboBox = QtGui.QComboBox(self.tab_21)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_18.addWidget(self.comboBox, 4, 4, 1, 2)
        self.label_7 = QtGui.QLabel(self.tab_21)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_18.addWidget(self.label_7, 5, 3, 1, 3)
        self.progressBar_2 = QtGui.QProgressBar(self.tab_21)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.gridLayout_18.addWidget(self.progressBar_2, 6, 0, 1, 5)
        self.pushButton_44 = QtGui.QPushButton(self.tab_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_44.sizePolicy().hasHeightForWidth())
        self.pushButton_44.setSizePolicy(sizePolicy)
        self.pushButton_44.setIcon(icon3)
        self.pushButton_44.setObjectName(_fromUtf8("pushButton_44"))
        self.gridLayout_18.addWidget(self.pushButton_44, 6, 5, 1, 1)
        self.tabWidget_3.addTab(self.tab_21, _fromUtf8(""))
        self.tab_22 = QtGui.QWidget()
        self.tab_22.setObjectName(_fromUtf8("tab_22"))
        self.gridLayout_19 = QtGui.QGridLayout(self.tab_22)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.frame_7 = QtGui.QFrame(self.tab_22)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_10 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.pushButton_51 = QtGui.QPushButton(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_51.sizePolicy().hasHeightForWidth())
        self.pushButton_51.setSizePolicy(sizePolicy)
        self.pushButton_51.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_51.setText(_fromUtf8(""))
        self.pushButton_51.setIcon(icon5)
        self.pushButton_51.setObjectName(_fromUtf8("pushButton_51"))
        self.gridLayout_10.addWidget(self.pushButton_51, 1, 1, 1, 1)
        self.pushButton_52 = QtGui.QPushButton(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_52.sizePolicy().hasHeightForWidth())
        self.pushButton_52.setSizePolicy(sizePolicy)
        self.pushButton_52.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_52.setText(_fromUtf8(""))
        self.pushButton_52.setIcon(icon6)
        self.pushButton_52.setObjectName(_fromUtf8("pushButton_52"))
        self.gridLayout_10.addWidget(self.pushButton_52, 1, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(46, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem3, 1, 6, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.frame_7)
        self.lineEdit_8.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(75, 25))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_10.addWidget(self.lineEdit_8, 1, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(46, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem4, 1, 0, 1, 1)
        self.pushButton_53 = QtGui.QPushButton(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_53.sizePolicy().hasHeightForWidth())
        self.pushButton_53.setSizePolicy(sizePolicy)
        self.pushButton_53.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_53.setText(_fromUtf8(""))
        self.pushButton_53.setIcon(icon7)
        self.pushButton_53.setObjectName(_fromUtf8("pushButton_53"))
        self.gridLayout_10.addWidget(self.pushButton_53, 1, 4, 1, 1)
        self.pushButton_54 = QtGui.QPushButton(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_54.sizePolicy().hasHeightForWidth())
        self.pushButton_54.setSizePolicy(sizePolicy)
        self.pushButton_54.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_54.setText(_fromUtf8(""))
        self.pushButton_54.setIcon(icon8)
        self.pushButton_54.setObjectName(_fromUtf8("pushButton_54"))
        self.gridLayout_10.addWidget(self.pushButton_54, 1, 5, 1, 1)
        self.graphicsView_7 = QtGui.QGraphicsView(self.frame_7)
        self.graphicsView_7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.graphicsView_7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.graphicsView_7.setObjectName(_fromUtf8("graphicsView_7"))
        self.gridLayout_10.addWidget(self.graphicsView_7, 0, 0, 1, 7)
        self.gridLayout_19.addWidget(self.frame_7, 0, 0, 6, 1)
        self.line_3 = QtGui.QFrame(self.tab_22)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_19.addWidget(self.line_3, 0, 1, 6, 1)
        self.label_8 = QtGui.QLabel(self.tab_22)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_19.addWidget(self.label_8, 0, 2, 1, 1)
        self.listWidget_7 = QtGui.QListWidget(self.tab_22)
        self.listWidget_7.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_7.setObjectName(_fromUtf8("listWidget_7"))
        self.gridLayout_19.addWidget(self.listWidget_7, 1, 2, 1, 3)
        self.pushButton_56 = QtGui.QPushButton(self.tab_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_56.sizePolicy().hasHeightForWidth())
        self.pushButton_56.setSizePolicy(sizePolicy)
        self.pushButton_56.setIcon(icon1)
        self.pushButton_56.setObjectName(_fromUtf8("pushButton_56"))
        self.gridLayout_19.addWidget(self.pushButton_56, 2, 3, 1, 1)
        self.pushButton_57 = QtGui.QPushButton(self.tab_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_57.sizePolicy().hasHeightForWidth())
        self.pushButton_57.setSizePolicy(sizePolicy)
        self.pushButton_57.setIcon(icon2)
        self.pushButton_57.setObjectName(_fromUtf8("pushButton_57"))
        self.gridLayout_19.addWidget(self.pushButton_57, 2, 4, 1, 1)
        self.line_4 = QtGui.QFrame(self.tab_22)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_19.addWidget(self.line_4, 3, 2, 1, 3)
        self.label_9 = QtGui.QLabel(self.tab_22)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_19.addWidget(self.label_9, 4, 2, 1, 2)
        self.lineEdit = QtGui.QLineEdit(self.tab_22)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_19.addWidget(self.lineEdit, 5, 2, 1, 2)
        self.progressBar_3 = QtGui.QProgressBar(self.tab_22)
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.gridLayout_19.addWidget(self.progressBar_3, 6, 0, 1, 4)
        self.pushButton_55 = QtGui.QPushButton(self.tab_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_55.sizePolicy().hasHeightForWidth())
        self.pushButton_55.setSizePolicy(sizePolicy)
        self.pushButton_55.setIcon(icon3)
        self.pushButton_55.setObjectName(_fromUtf8("pushButton_55"))
        self.gridLayout_19.addWidget(self.pushButton_55, 6, 4, 1, 1)
        self.tabWidget_3.addTab(self.tab_22, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("img/align.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon9, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_11.addWidget(self.label, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.tab_2)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_11.addWidget(self.line, 0, 1, 10, 2)
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_11.addWidget(self.label_4, 0, 3, 1, 1)
        self.frame_2 = QtGui.QFrame(self.tab_2)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.pushButton_17 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_17.setText(_fromUtf8(""))
        self.pushButton_17.setIcon(icon8)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.gridLayout_8.addWidget(self.pushButton_17, 2, 5, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 2, 0, 1, 1)
        self.pushButton_15 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_15.setText(_fromUtf8(""))
        self.pushButton_15.setIcon(icon6)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.gridLayout_8.addWidget(self.pushButton_15, 2, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem6, 2, 6, 1, 1)
        self.graphicsView_2 = QtGui.QGraphicsView(self.frame_2)
        self.graphicsView_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.graphicsView_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.gridLayout_8.addWidget(self.graphicsView_2, 0, 0, 2, 7)
        self.lineEdit_2 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(75, 25))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_8.addWidget(self.lineEdit_2, 2, 3, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_14.setText(_fromUtf8(""))
        self.pushButton_14.setIcon(icon5)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout_8.addWidget(self.pushButton_14, 2, 1, 1, 1)
        self.pushButton_16 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_16.setText(_fromUtf8(""))
        self.pushButton_16.setIcon(icon7)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.gridLayout_8.addWidget(self.pushButton_16, 2, 4, 1, 1)
        self.gridLayout_11.addWidget(self.frame_2, 1, 0, 9, 1)
        self.listWidget_5 = QtGui.QListWidget(self.tab_2)
        self.listWidget_5.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_5.setObjectName(_fromUtf8("listWidget_5"))
        self.gridLayout_11.addWidget(self.listWidget_5, 1, 3, 1, 3)
        self.pushButton_36 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_36.sizePolicy().hasHeightForWidth())
        self.pushButton_36.setSizePolicy(sizePolicy)
        self.pushButton_36.setIcon(icon1)
        self.pushButton_36.setObjectName(_fromUtf8("pushButton_36"))
        self.gridLayout_11.addWidget(self.pushButton_36, 2, 4, 1, 1)
        self.pushButton_35 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_35.sizePolicy().hasHeightForWidth())
        self.pushButton_35.setSizePolicy(sizePolicy)
        self.pushButton_35.setIcon(icon2)
        self.pushButton_35.setObjectName(_fromUtf8("pushButton_35"))
        self.gridLayout_11.addWidget(self.pushButton_35, 2, 5, 1, 1)
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_11.addWidget(self.line_2, 3, 3, 1, 3)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_11.addWidget(self.label_5, 4, 3, 1, 1)
        self.listWidget_6 = QtGui.QListWidget(self.tab_2)
        self.listWidget_6.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_6.setObjectName(_fromUtf8("listWidget_6"))
        self.gridLayout_11.addWidget(self.listWidget_6, 5, 3, 1, 3)
        self.checkBox_7 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.gridLayout_11.addWidget(self.checkBox_7, 6, 2, 1, 3)
        self.pushButton_38 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_38.sizePolicy().hasHeightForWidth())
        self.pushButton_38.setSizePolicy(sizePolicy)
        self.pushButton_38.setIcon(icon1)
        self.pushButton_38.setObjectName(_fromUtf8("pushButton_38"))
        self.gridLayout_11.addWidget(self.pushButton_38, 7, 4, 1, 1)
        self.pushButton_37 = QtGui.QPushButton(self.tab_2)
        self.pushButton_37.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_37.sizePolicy().hasHeightForWidth())
        self.pushButton_37.setSizePolicy(sizePolicy)
        self.pushButton_37.setIcon(icon2)
        self.pushButton_37.setObjectName(_fromUtf8("pushButton_37"))
        self.gridLayout_11.addWidget(self.pushButton_37, 7, 5, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_11.addWidget(self.lineEdit_5, 8, 2, 1, 4)
        self.checkBox_4 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_11.addWidget(self.checkBox_4, 9, 2, 1, 3)
        self.progressBar_4 = QtGui.QProgressBar(self.tab_2)
        self.progressBar_4.setProperty("value", 24)
        self.progressBar_4.setObjectName(_fromUtf8("progressBar_4"))
        self.gridLayout_11.addWidget(self.progressBar_4, 10, 0, 1, 5)
        self.pushButton_39 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_39.sizePolicy().hasHeightForWidth())
        self.pushButton_39.setSizePolicy(sizePolicy)
        self.pushButton_39.setIcon(icon3)
        self.pushButton_39.setObjectName(_fromUtf8("pushButton_39"))
        self.gridLayout_11.addWidget(self.pushButton_39, 10, 5, 1, 1)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("img/phot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon10, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("img/wcs.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon11, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_10 = QtGui.QLabel(self.tab_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_12.addWidget(self.label_10, 0, 0, 1, 1)
        self.line_7 = QtGui.QFrame(self.tab_5)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_12.addWidget(self.line_7, 0, 1, 10, 1)
        self.label_14 = QtGui.QLabel(self.tab_5)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_12.addWidget(self.label_14, 0, 2, 1, 1)
        self.listWidget_8 = QtGui.QListWidget(self.tab_5)
        self.listWidget_8.setObjectName(_fromUtf8("listWidget_8"))
        self.gridLayout_12.addWidget(self.listWidget_8, 1, 0, 9, 1)
        self.listWidget_9 = QtGui.QListWidget(self.tab_5)
        self.listWidget_9.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_9.setObjectName(_fromUtf8("listWidget_9"))
        self.gridLayout_12.addWidget(self.listWidget_9, 1, 2, 1, 4)
        self.pushButton_60 = QtGui.QPushButton(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_60.sizePolicy().hasHeightForWidth())
        self.pushButton_60.setSizePolicy(sizePolicy)
        self.pushButton_60.setIcon(icon1)
        self.pushButton_60.setObjectName(_fromUtf8("pushButton_60"))
        self.gridLayout_12.addWidget(self.pushButton_60, 2, 3, 1, 1)
        self.pushButton_59 = QtGui.QPushButton(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_59.sizePolicy().hasHeightForWidth())
        self.pushButton_59.setSizePolicy(sizePolicy)
        self.pushButton_59.setIcon(icon2)
        self.pushButton_59.setObjectName(_fromUtf8("pushButton_59"))
        self.gridLayout_12.addWidget(self.pushButton_59, 2, 4, 1, 2)
        self.line_8 = QtGui.QFrame(self.tab_5)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_12.addWidget(self.line_8, 3, 2, 1, 4)
        self.label_15 = QtGui.QLabel(self.tab_5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_12.addWidget(self.label_15, 4, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_5)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_12.addWidget(self.label_16, 6, 2, 1, 1)
        self.checkBox_5 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.gridLayout_12.addWidget(self.checkBox_5, 8, 2, 1, 4)
        self.progressBar_5 = QtGui.QProgressBar(self.tab_5)
        self.progressBar_5.setProperty("value", 24)
        self.progressBar_5.setObjectName(_fromUtf8("progressBar_5"))
        self.gridLayout_12.addWidget(self.progressBar_5, 10, 0, 1, 5)
        self.pushButton_58 = QtGui.QPushButton(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_58.sizePolicy().hasHeightForWidth())
        self.pushButton_58.setSizePolicy(sizePolicy)
        self.pushButton_58.setIcon(icon3)
        self.pushButton_58.setObjectName(_fromUtf8("pushButton_58"))
        self.gridLayout_12.addWidget(self.pushButton_58, 10, 5, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_12.addWidget(self.lineEdit_4, 7, 2, 1, 4)
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_12.addWidget(self.lineEdit_3, 5, 2, 1, 4)
        self.comboBox_2 = QtGui.QComboBox(self.tab_5)
        self.comboBox_2.setEnabled(False)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.gridLayout_12.addWidget(self.comboBox_2, 9, 2, 1, 4)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("img/head.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_5, icon12, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tab_11)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_17 = QtGui.QLabel(self.tab_11)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_13.addWidget(self.label_17, 0, 0, 1, 1)
        self.line_9 = QtGui.QFrame(self.tab_11)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout_13.addWidget(self.line_9, 0, 1, 17, 1)
        self.label_18 = QtGui.QLabel(self.tab_11)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_13.addWidget(self.label_18, 0, 2, 1, 2)
        self.label_20 = QtGui.QLabel(self.tab_11)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_13.addWidget(self.label_20, 2, 2, 1, 2)
        self.lineEdit_9 = QtGui.QLineEdit(self.tab_11)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_13.addWidget(self.lineEdit_9, 3, 3, 1, 3)
        self.label_21 = QtGui.QLabel(self.tab_11)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_13.addWidget(self.label_21, 4, 3, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.tab_11)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout_13.addWidget(self.lineEdit_10, 5, 3, 1, 3)
        self.label_22 = QtGui.QLabel(self.tab_11)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_13.addWidget(self.label_22, 6, 3, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.tab_11)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_13.addWidget(self.lineEdit_11, 7, 3, 1, 3)
        self.label_23 = QtGui.QLabel(self.tab_11)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_13.addWidget(self.label_23, 8, 3, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(self.tab_11)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout_13.addWidget(self.lineEdit_12, 9, 3, 1, 3)
        self.label_24 = QtGui.QLabel(self.tab_11)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_13.addWidget(self.label_24, 10, 3, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.tab_11)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout_13.addWidget(self.lineEdit_13, 11, 3, 1, 3)
        self.label_25 = QtGui.QLabel(self.tab_11)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_13.addWidget(self.label_25, 12, 3, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.tab_11)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_13.addWidget(self.lineEdit_14, 13, 3, 1, 3)
        self.label_19 = QtGui.QLabel(self.tab_11)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_13.addWidget(self.label_19, 14, 3, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.tab_11)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_13.addWidget(self.textEdit, 15, 3, 1, 3)
        self.pushButton_63 = QtGui.QPushButton(self.tab_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_63.sizePolicy().hasHeightForWidth())
        self.pushButton_63.setSizePolicy(sizePolicy)
        self.pushButton_63.setIcon(icon1)
        self.pushButton_63.setObjectName(_fromUtf8("pushButton_63"))
        self.gridLayout_13.addWidget(self.pushButton_63, 16, 4, 1, 1)
        self.pushButton_62 = QtGui.QPushButton(self.tab_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_62.sizePolicy().hasHeightForWidth())
        self.pushButton_62.setSizePolicy(sizePolicy)
        self.pushButton_62.setIcon(icon2)
        self.pushButton_62.setObjectName(_fromUtf8("pushButton_62"))
        self.gridLayout_13.addWidget(self.pushButton_62, 16, 5, 1, 1)
        self.progressBar_6 = QtGui.QProgressBar(self.tab_11)
        self.progressBar_6.setProperty("value", 24)
        self.progressBar_6.setObjectName(_fromUtf8("progressBar_6"))
        self.gridLayout_13.addWidget(self.progressBar_6, 17, 0, 1, 5)
        self.pushButton_61 = QtGui.QPushButton(self.tab_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_61.sizePolicy().hasHeightForWidth())
        self.pushButton_61.setSizePolicy(sizePolicy)
        self.pushButton_61.setIcon(icon3)
        self.pushButton_61.setObjectName(_fromUtf8("pushButton_61"))
        self.gridLayout_13.addWidget(self.pushButton_61, 17, 5, 1, 1)
        self.listWidget_10 = QtGui.QListWidget(self.tab_11)
        self.listWidget_10.setObjectName(_fromUtf8("listWidget_10"))
        self.gridLayout_13.addWidget(self.listWidget_10, 1, 0, 16, 1)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("img/observatory.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_11, icon13, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_11 = QtGui.QLabel(self.tab_6)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_14.addWidget(self.label_11, 0, 0, 1, 1)
        self.tabWidget_4 = QtGui.QTabWidget(self.tab_6)
        self.tabWidget_4.setObjectName(_fromUtf8("tabWidget_4"))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tab_12)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.textEdit_2 = QtGui.QTextEdit(self.tab_12)
        self.textEdit_2.setEnabled(False)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.gridLayout_15.addWidget(self.textEdit_2, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_12, _fromUtf8(""))
        self.tab_14 = QtGui.QWidget()
        self.tab_14.setObjectName(_fromUtf8("tab_14"))
        self.gridLayout_16 = QtGui.QGridLayout(self.tab_14)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.textEdit_3 = QtGui.QTextEdit(self.tab_14)
        self.textEdit_3.setEnabled(False)
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        self.gridLayout_16.addWidget(self.textEdit_3, 0, 0, 1, 3)
        spacerItem7 = QtGui.QSpacerItem(581, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem7, 1, 0, 1, 1)
        self.pushButton_41 = QtGui.QPushButton(self.tab_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_41.sizePolicy().hasHeightForWidth())
        self.pushButton_41.setSizePolicy(sizePolicy)
        self.pushButton_41.setIcon(icon1)
        self.pushButton_41.setObjectName(_fromUtf8("pushButton_41"))
        self.gridLayout_16.addWidget(self.pushButton_41, 1, 1, 1, 1)
        self.pushButton_40 = QtGui.QPushButton(self.tab_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_40.sizePolicy().hasHeightForWidth())
        self.pushButton_40.setSizePolicy(sizePolicy)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("img/update.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_40.setIcon(icon14)
        self.pushButton_40.setObjectName(_fromUtf8("pushButton_40"))
        self.gridLayout_16.addWidget(self.pushButton_40, 1, 2, 1, 1)
        self.tabWidget_4.addTab(self.tab_14, _fromUtf8(""))
        self.tab_15 = QtGui.QWidget()
        self.tab_15.setObjectName(_fromUtf8("tab_15"))
        self.gridLayout_17 = QtGui.QGridLayout(self.tab_15)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.textEdit_4 = QtGui.QTextEdit(self.tab_15)
        self.textEdit_4.setEnabled(False)
        self.textEdit_4.setObjectName(_fromUtf8("textEdit_4"))
        self.gridLayout_17.addWidget(self.textEdit_4, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_15, _fromUtf8(""))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.gridLayout_20 = QtGui.QGridLayout(self.tab_13)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.textEdit_5 = QtGui.QTextEdit(self.tab_13)
        self.textEdit_5.setEnabled(False)
        self.textEdit_5.setObjectName(_fromUtf8("textEdit_5"))
        self.gridLayout_20.addWidget(self.textEdit_5, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_13, _fromUtf8(""))
        self.gridLayout_14.addWidget(self.tabWidget_4, 1, 0, 1, 1)
        self.checkBox_6 = QtGui.QCheckBox(self.tab_6)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.gridLayout_14.addWidget(self.checkBox_6, 2, 0, 1, 1)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("img/help-about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_6, icon15, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "MYRaf", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Form", "Bias", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("Form", "Dark", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("Form", "Flat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Form", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Form", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), QtGui.QApplication.translate("Form", "Images", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("Form", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("Form", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), QtGui.QApplication.translate("Form", "Bias", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("Form", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("Form", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), QtGui.QApplication.translate("Form", "Dark", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("Form", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("Form", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), QtGui.QApplication.translate("Form", "Flat", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Form", ":go", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Calibration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Images:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_50.setText(QtGui.QApplication.translate("Form", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_49.setText(QtGui.QApplication.translate("Form", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Method:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Form", "Method 1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Form", "Method 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Alignment method\n"
"selection", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_44.setText(QtGui.QApplication.translate("Form", ":go", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_21), QtGui.QApplication.translate("Form", "Auto Align", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Images:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_56.setText(QtGui.QApplication.translate("Form", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_57.setText(QtGui.QApplication.translate("Form", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Coordinates:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_55.setText(QtGui.QApplication.translate("Form", ":go", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_22), QtGui.QApplication.translate("Form", "Manual Align", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Form", "Align", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Preview:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Images:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_36.setText(QtGui.QApplication.translate("Form", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_35.setText(QtGui.QApplication.translate("Form", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Coor List:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("Form", "Auto Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_38.setText(QtGui.QApplication.translate("Form", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_37.setText(QtGui.QApplication.translate("Form", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("Form", "Auto Align", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_39.setText(QtGui.QApplication.translate("Form", ":go", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Photometry", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Form", "WCS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Header:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Images:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_60.setText(QtGui.QApplication.translate("Form", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_59.setText(QtGui.QApplication.translate("Form", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Field:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("Form", "Use value of an existing field", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_58.setText(QtGui.QApplication.translate("Form", ":go", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("Form", "Header Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Observatory List:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Details:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Form", "Observatory:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Form", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Form", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Form", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Form", "Atitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Form", "Time zone:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Form", "Notes:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_63.setText(QtGui.QApplication.translate("Form", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_62.setText(QtGui.QApplication.translate("Form", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_61.setText(QtGui.QApplication.translate("Form", ":go", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), QtGui.QApplication.translate("Form", "Observatory Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Version 2 Beta", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), QtGui.QApplication.translate("Form", "MYRaf Help", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_41.setText(QtGui.QApplication.translate("Form", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_40.setText(QtGui.QApplication.translate("Form", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_14), QtGui.QApplication.translate("Form", "Log Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_15), QtGui.QApplication.translate("Form", "License", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), QtGui.QApplication.translate("Form", "Credits", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("Form", "Enable sturtup helping", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("Form", "Help", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

