# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/settings.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindowSett(object):
    def setupUi(self, MainWindowSett):
        MainWindowSett.setObjectName(_fromUtf8("MainWindowSett"))
        MainWindowSett.resize(704, 653)
        self.centralwidget = QtGui.QWidget(MainWindowSett)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(20, 0))
        self.label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(529, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.dial = QtGui.QDial(self.groupBox)
        self.dial.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.dial.setMouseTracking(True)
        self.dial.setMinimum(1)
        self.dial.setMaximum(8)
        self.dial.setPageStep(1)
        self.dial.setSliderPosition(1)
        self.dial.setOrientation(QtCore.Qt.Horizontal)
        self.dial.setInvertedAppearance(False)
        self.dial.setInvertedControls(False)
        self.dial.setWrapping(False)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.gridLayout.addWidget(self.dial, 0, 0, 1, 3)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_21 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_21.setFlat(True)
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.gridLayout_37 = QtGui.QGridLayout(self.groupBox_21)
        self.gridLayout_37.setObjectName(_fromUtf8("gridLayout_37"))
        self.gridLayout_54 = QtGui.QGridLayout()
        self.gridLayout_54.setObjectName(_fromUtf8("gridLayout_54"))
        self.label_13 = QtGui.QLabel(self.groupBox_21)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_54.addWidget(self.label_13, 0, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_21)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout_54.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_21)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_54.addWidget(self.label_18, 1, 0, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_21)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.gridLayout_54.addWidget(self.comboBox_3, 1, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_21)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_54.addWidget(self.label_19, 2, 0, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.groupBox_21)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_54.addWidget(self.lineEdit_9, 2, 1, 1, 1)
        self.gridLayout_37.addLayout(self.gridLayout_54, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 142, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_37.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_21, 0, 0, 1, 1)
        self.groupBox_22 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_22.setObjectName(_fromUtf8("groupBox_22"))
        self.gridLayout_38 = QtGui.QGridLayout(self.groupBox_22)
        self.gridLayout_38.setObjectName(_fromUtf8("gridLayout_38"))
        self.gridLayout_56 = QtGui.QGridLayout()
        self.gridLayout_56.setObjectName(_fromUtf8("gridLayout_56"))
        self.label_29 = QtGui.QLabel(self.groupBox_22)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_56.addWidget(self.label_29, 0, 0, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.groupBox_22)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.gridLayout_56.addWidget(self.comboBox_4, 0, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_22)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_56.addWidget(self.label_30, 1, 0, 1, 1)
        self.comboBox_5 = QtGui.QComboBox(self.groupBox_22)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.gridLayout_56.addWidget(self.comboBox_5, 1, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupBox_22)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_56.addWidget(self.label_35, 2, 0, 1, 1)
        self.comboBox_8 = QtGui.QComboBox(self.groupBox_22)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.gridLayout_56.addWidget(self.comboBox_8, 2, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_22)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_56.addWidget(self.label_28, 3, 0, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.groupBox_22)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout_56.addWidget(self.lineEdit_10, 3, 1, 1, 1)
        self.gridLayout_38.addLayout(self.gridLayout_56, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 113, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_38.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_22, 0, 1, 1, 1)
        self.groupBox_23 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_23.setObjectName(_fromUtf8("groupBox_23"))
        self.gridLayout_50 = QtGui.QGridLayout(self.groupBox_23)
        self.gridLayout_50.setObjectName(_fromUtf8("gridLayout_50"))
        self.gridLayout_57 = QtGui.QGridLayout()
        self.gridLayout_57.setObjectName(_fromUtf8("gridLayout_57"))
        self.label_32 = QtGui.QLabel(self.groupBox_23)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_57.addWidget(self.label_32, 0, 0, 1, 1)
        self.comboBox_6 = QtGui.QComboBox(self.groupBox_23)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.gridLayout_57.addWidget(self.comboBox_6, 0, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBox_23)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_57.addWidget(self.label_33, 1, 0, 1, 1)
        self.comboBox_7 = QtGui.QComboBox(self.groupBox_23)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.gridLayout_57.addWidget(self.comboBox_7, 1, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_23)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_57.addWidget(self.label_36, 2, 0, 1, 1)
        self.comboBox_9 = QtGui.QComboBox(self.groupBox_23)
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.gridLayout_57.addWidget(self.comboBox_9, 2, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_23)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_57.addWidget(self.label_31, 3, 0, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.groupBox_23)
        self.lineEdit_11.setText(_fromUtf8(""))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_57.addWidget(self.lineEdit_11, 3, 1, 1, 1)
        self.gridLayout_50.addLayout(self.gridLayout_57, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 113, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_50.addItem(spacerItem4, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_23, 1, 0, 1, 1)
        self.groupBox_24 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_24.setObjectName(_fromUtf8("groupBox_24"))
        self.gridLayout_51 = QtGui.QGridLayout(self.groupBox_24)
        self.gridLayout_51.setObjectName(_fromUtf8("gridLayout_51"))
        self.gridLayout_91 = QtGui.QGridLayout()
        self.gridLayout_91.setObjectName(_fromUtf8("gridLayout_91"))
        self.label_37 = QtGui.QLabel(self.groupBox_24)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_91.addWidget(self.label_37, 0, 0, 1, 1)
        self.comboBox_10 = QtGui.QComboBox(self.groupBox_24)
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.gridLayout_91.addWidget(self.comboBox_10, 0, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupBox_24)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_91.addWidget(self.label_34, 1, 0, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(self.groupBox_24)
        self.lineEdit_12.setText(_fromUtf8(""))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout_91.addWidget(self.lineEdit_12, 1, 1, 1, 1)
        self.gridLayout_51.addLayout(self.gridLayout_91, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 171, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_51.addItem(spacerItem5, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_24, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox_14 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.gridLayout_59 = QtGui.QGridLayout(self.groupBox_14)
        self.gridLayout_59.setObjectName(_fromUtf8("gridLayout_59"))
        self.label_40 = QtGui.QLabel(self.groupBox_14)
        self.label_40.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_40.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_59.addWidget(self.label_40, 0, 0, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_2.setDecimals(0)
        self.doubleSpinBox_2.setMaximum(1000.0)
        self.doubleSpinBox_2.setProperty("value", 25.0)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout_59.addWidget(self.doubleSpinBox_2, 0, 1, 1, 1)
        self.label_42 = QtGui.QLabel(self.groupBox_14)
        self.label_42.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_42.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_59.addWidget(self.label_42, 1, 0, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox.setDecimals(0)
        self.doubleSpinBox.setMaximum(1000.0)
        self.doubleSpinBox.setProperty("value", 5.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout_59.addWidget(self.doubleSpinBox, 1, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.groupBox_14)
        self.label_46.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_46.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_59.addWidget(self.label_46, 2, 0, 1, 1)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_3.setDecimals(0)
        self.doubleSpinBox_3.setMaximum(1000.0)
        self.doubleSpinBox_3.setProperty("value", 10.0)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.gridLayout_59.addWidget(self.doubleSpinBox_3, 2, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_14, 0, 0, 1, 1)
        self.groupBox_13 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.gridLayout_53 = QtGui.QGridLayout(self.groupBox_13)
        self.gridLayout_53.setObjectName(_fromUtf8("gridLayout_53"))
        self.label_39 = QtGui.QLabel(self.groupBox_13)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_53.addWidget(self.label_39, 1, 0, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.groupBox_13)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout_53.addWidget(self.lineEdit_13, 0, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBox_13)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_53.addWidget(self.label_38, 0, 0, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.groupBox_13)
        self.lineEdit_14.setMaxLength(8)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_53.addWidget(self.lineEdit_14, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_13, 1, 0, 1, 1)
        self.groupBox_15 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_15)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.label_44 = QtGui.QLabel(self.groupBox_15)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_20.addWidget(self.label_44, 0, 0, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(self.groupBox_15)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.gridLayout_20.addWidget(self.lineEdit_15, 0, 1, 1, 1)
        self.label_45 = QtGui.QLabel(self.groupBox_15)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_20.addWidget(self.label_45, 1, 0, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(self.groupBox_15)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout_20.addWidget(self.lineEdit_16, 1, 1, 1, 1)
        self.label_57 = QtGui.QLabel(self.groupBox_15)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_20.addWidget(self.label_57, 2, 0, 1, 1)
        self.lineEdit_26 = QtGui.QLineEdit(self.groupBox_15)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.gridLayout_20.addWidget(self.lineEdit_26, 2, 1, 1, 1)
        self.label_77 = QtGui.QLabel(self.groupBox_15)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.gridLayout_20.addWidget(self.label_77, 3, 0, 1, 1)
        self.lineEdit_29 = QtGui.QLineEdit(self.groupBox_15)
        self.lineEdit_29.setText(_fromUtf8(""))
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.gridLayout_20.addWidget(self.lineEdit_29, 3, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_15, 2, 0, 1, 1)
        self.groupBox_20 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.gridLayout_71 = QtGui.QGridLayout(self.groupBox_20)
        self.gridLayout_71.setObjectName(_fromUtf8("gridLayout_71"))
        self.label_65 = QtGui.QLabel(self.groupBox_20)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_71.addWidget(self.label_65, 0, 0, 1, 1)
        self.lineEdit_22 = QtGui.QLineEdit(self.groupBox_20)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.gridLayout_71.addWidget(self.lineEdit_22, 0, 1, 1, 1)
        self.label_66 = QtGui.QLabel(self.groupBox_20)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_71.addWidget(self.label_66, 1, 0, 1, 1)
        self.lineEdit_23 = QtGui.QLineEdit(self.groupBox_20)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.gridLayout_71.addWidget(self.lineEdit_23, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_20, 3, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_17 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_17.setMinimumSize(QtCore.QSize(250, 160))
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.gridLayout_69 = QtGui.QGridLayout(self.groupBox_17)
        self.gridLayout_69.setObjectName(_fromUtf8("gridLayout_69"))
        self.label_48 = QtGui.QLabel(self.groupBox_17)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_69.addWidget(self.label_48, 2, 0, 1, 1)
        self.lineEdit_25 = QtGui.QLineEdit(self.groupBox_17)
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.gridLayout_69.addWidget(self.lineEdit_25, 6, 2, 1, 1)
        self.label_47 = QtGui.QLabel(self.groupBox_17)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_69.addWidget(self.label_47, 0, 0, 1, 1)
        self.lineEdit_18 = QtGui.QLineEdit(self.groupBox_17)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.gridLayout_69.addWidget(self.lineEdit_18, 0, 2, 1, 1)
        self.lineEdit_17 = QtGui.QLineEdit(self.groupBox_17)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.gridLayout_69.addWidget(self.lineEdit_17, 2, 2, 1, 1)
        self.label_67 = QtGui.QLabel(self.groupBox_17)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_69.addWidget(self.label_67, 5, 0, 1, 1)
        self.lineEdit_24 = QtGui.QLineEdit(self.groupBox_17)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.gridLayout_69.addWidget(self.lineEdit_24, 5, 2, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.groupBox_17)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_69.addWidget(self.checkBox_4, 6, 0, 1, 1)
        self.checkBox_12 = QtGui.QCheckBox(self.groupBox_17)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.gridLayout_69.addWidget(self.checkBox_12, 1, 0, 1, 3)
        self.gridLayout_5.addWidget(self.groupBox_17, 0, 0, 1, 1)
        self.groupBox_19 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.gridLayout_41 = QtGui.QGridLayout(self.groupBox_19)
        self.gridLayout_41.setObjectName(_fromUtf8("gridLayout_41"))
        self.label_64 = QtGui.QLabel(self.groupBox_19)
        self.label_64.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_64.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_41.addWidget(self.label_64, 0, 0, 1, 1)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.groupBox_19)
        self.doubleSpinBox_4.setDecimals(0)
        self.doubleSpinBox_4.setMinimum(2.0)
        self.doubleSpinBox_4.setMaximum(100.0)
        self.doubleSpinBox_4.setProperty("value", 2.0)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.gridLayout_41.addWidget(self.doubleSpinBox_4, 0, 1, 1, 1)
        self.label_68 = QtGui.QLabel(self.groupBox_19)
        self.label_68.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_68.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_41.addWidget(self.label_68, 1, 0, 1, 1)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.groupBox_19)
        self.doubleSpinBox_5.setDecimals(0)
        self.doubleSpinBox_5.setMinimum(1.0)
        self.doubleSpinBox_5.setMaximum(100.0)
        self.doubleSpinBox_5.setProperty("value", 4.0)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.gridLayout_41.addWidget(self.doubleSpinBox_5, 1, 1, 1, 1)
        self.label_69 = QtGui.QLabel(self.groupBox_19)
        self.label_69.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_69.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_41.addWidget(self.label_69, 2, 0, 1, 1)
        self.doubleSpinBox_6 = QtGui.QDoubleSpinBox(self.groupBox_19)
        self.doubleSpinBox_6.setDecimals(0)
        self.doubleSpinBox_6.setMinimum(1.0)
        self.doubleSpinBox_6.setMaximum(100.0)
        self.doubleSpinBox_6.setProperty("value", 9.0)
        self.doubleSpinBox_6.setObjectName(_fromUtf8("doubleSpinBox_6"))
        self.gridLayout_41.addWidget(self.doubleSpinBox_6, 2, 1, 1, 1)
        self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(self.groupBox_19)
        self.doubleSpinBox_7.setDecimals(0)
        self.doubleSpinBox_7.setMinimum(1.0)
        self.doubleSpinBox_7.setMaximum(10000.0)
        self.doubleSpinBox_7.setProperty("value", 25.0)
        self.doubleSpinBox_7.setObjectName(_fromUtf8("doubleSpinBox_7"))
        self.gridLayout_41.addWidget(self.doubleSpinBox_7, 4, 1, 1, 1)
        self.label_70 = QtGui.QLabel(self.groupBox_19)
        self.label_70.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_41.addWidget(self.label_70, 4, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_19, 1, 0, 1, 1)
        self.groupBox_31 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_31.setObjectName(_fromUtf8("groupBox_31"))
        self.gridLayout_68 = QtGui.QGridLayout(self.groupBox_31)
        self.gridLayout_68.setObjectName(_fromUtf8("gridLayout_68"))
        self.pushButton_50 = QtGui.QPushButton(self.groupBox_31)
        self.pushButton_50.setObjectName(_fromUtf8("pushButton_50"))
        self.gridLayout_68.addWidget(self.pushButton_50, 1, 1, 1, 1)
        self.listWidget_20 = QtGui.QListWidget(self.groupBox_31)
        self.listWidget_20.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_20.setObjectName(_fromUtf8("listWidget_20"))
        self.gridLayout_68.addWidget(self.listWidget_20, 0, 2, 3, 1)
        self.pushButton_49 = QtGui.QPushButton(self.groupBox_31)
        self.pushButton_49.setObjectName(_fromUtf8("pushButton_49"))
        self.gridLayout_68.addWidget(self.pushButton_49, 0, 1, 1, 1)
        self.pushButton_51 = QtGui.QPushButton(self.groupBox_31)
        self.pushButton_51.setObjectName(_fromUtf8("pushButton_51"))
        self.gridLayout_68.addWidget(self.pushButton_51, 2, 1, 1, 1)
        self.listWidget_19 = QtGui.QListWidget(self.groupBox_31)
        self.listWidget_19.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_19.setObjectName(_fromUtf8("listWidget_19"))
        self.gridLayout_68.addWidget(self.listWidget_19, 0, 0, 3, 1)
        self.gridLayout_5.addWidget(self.groupBox_31, 2, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.checkBox_16 = QtGui.QCheckBox(self.tab_4)
        self.checkBox_16.setChecked(True)
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.gridLayout_8.addWidget(self.checkBox_16, 0, 0, 1, 2)
        self.label_74 = QtGui.QLabel(self.tab_4)
        self.label_74.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.gridLayout_8.addWidget(self.label_74, 1, 0, 1, 1)
        self.doubleSpinBox_10 = QtGui.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_10.setDecimals(7)
        self.doubleSpinBox_10.setMaximum(100000000.0)
        self.doubleSpinBox_10.setSingleStep(0.1)
        self.doubleSpinBox_10.setProperty("value", 2.2)
        self.doubleSpinBox_10.setObjectName(_fromUtf8("doubleSpinBox_10"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_10, 1, 1, 1, 1)
        self.label_75 = QtGui.QLabel(self.tab_4)
        self.label_75.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout_8.addWidget(self.label_75, 2, 0, 1, 1)
        self.doubleSpinBox_11 = QtGui.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_11.setDecimals(7)
        self.doubleSpinBox_11.setMaximum(100000000.0)
        self.doubleSpinBox_11.setSingleStep(0.1)
        self.doubleSpinBox_11.setProperty("value", 10.0)
        self.doubleSpinBox_11.setObjectName(_fromUtf8("doubleSpinBox_11"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_11, 2, 1, 1, 1)
        self.label_76 = QtGui.QLabel(self.tab_4)
        self.label_76.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout_8.addWidget(self.label_76, 3, 0, 1, 1)
        self.doubleSpinBox_12 = QtGui.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_12.setDecimals(7)
        self.doubleSpinBox_12.setMaximum(100000000.0)
        self.doubleSpinBox_12.setSingleStep(0.1)
        self.doubleSpinBox_12.setProperty("value", 5.0)
        self.doubleSpinBox_12.setObjectName(_fromUtf8("doubleSpinBox_12"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_12, 3, 1, 1, 1)
        self.label_79 = QtGui.QLabel(self.tab_4)
        self.label_79.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.gridLayout_8.addWidget(self.label_79, 4, 0, 1, 1)
        self.doubleSpinBox_13 = QtGui.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_13.setDecimals(7)
        self.doubleSpinBox_13.setMaximum(100000000.0)
        self.doubleSpinBox_13.setSingleStep(0.1)
        self.doubleSpinBox_13.setProperty("value", 0.3)
        self.doubleSpinBox_13.setObjectName(_fromUtf8("doubleSpinBox_13"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_13, 4, 1, 1, 1)
        self.label_78 = QtGui.QLabel(self.tab_4)
        self.label_78.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.gridLayout_8.addWidget(self.label_78, 5, 0, 1, 1)
        self.doubleSpinBox_14 = QtGui.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_14.setDecimals(7)
        self.doubleSpinBox_14.setMaximum(100000000.0)
        self.doubleSpinBox_14.setSingleStep(0.1)
        self.doubleSpinBox_14.setProperty("value", 5.0)
        self.doubleSpinBox_14.setObjectName(_fromUtf8("doubleSpinBox_14"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_14, 5, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 300, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_72 = QtGui.QLabel(self.tab_5)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout_10.addWidget(self.label_72, 0, 0, 1, 1)
        self.lineEdit_27 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.gridLayout_10.addWidget(self.lineEdit_27, 0, 1, 1, 1)
        self.label_73 = QtGui.QLabel(self.tab_5)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout_10.addWidget(self.label_73, 1, 0, 1, 1)
        self.lineEdit_28 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.gridLayout_10.addWidget(self.lineEdit_28, 1, 1, 1, 1)
        self.groupBox_36 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_36.setObjectName(_fromUtf8("groupBox_36"))
        self.gridLayout_84 = QtGui.QGridLayout(self.groupBox_36)
        self.gridLayout_84.setObjectName(_fromUtf8("gridLayout_84"))
        self.radioButton = QtGui.QRadioButton(self.groupBox_36)
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout_84.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox_36)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout_84.addWidget(self.radioButton_2, 1, 0, 1, 1)
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox_36)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.gridLayout_84.addWidget(self.radioButton_3, 2, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_36, 2, 0, 1, 2)
        self.checkBox_18 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_18.setChecked(True)
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.gridLayout_10.addWidget(self.checkBox_18, 3, 0, 1, 2)
        self.checkBox_19 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.gridLayout_10.addWidget(self.checkBox_19, 4, 0, 1, 2)
        spacerItem7 = QtGui.QSpacerItem(20, 253, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem7, 5, 0, 1, 2)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_12.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_12.addWidget(self.lineEdit_2, 0, 1, 1, 2)
        spacerItem8 = QtGui.QSpacerItem(197, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem8, 1, 0, 1, 2)
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_12.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_11.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboBox_11 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_11.setObjectName(_fromUtf8("comboBox_11"))
        self.gridLayout_11.addWidget(self.comboBox_11, 0, 1, 1, 2)
        spacerItem9 = QtGui.QSpacerItem(197, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem9, 1, 0, 1, 2)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_11.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_2, 0, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 366, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem10, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 2)
        spacerItem11 = QtGui.QSpacerItem(592, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 1, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_3.addWidget(self.pushButton, 1, 1, 1, 1)
        MainWindowSett.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindowSett)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 704, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindowSett.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindowSett)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindowSett.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowSett)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_5.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindowSett)

    def retranslateUi(self, MainWindowSett):
        MainWindowSett.setWindowTitle(_translate("MainWindowSett", "MYRaf3 - Settings", None))
        self.groupBox.setTitle(_translate("MainWindowSett", "CPU(s) to Use", None))
        self.label.setText(_translate("MainWindowSett", "of", None))
        self.label_2.setText(_translate("MainWindowSett", "8", None))
        self.label_5.setText(_translate("MainWindowSett", "1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindowSett", "General", None))
        self.groupBox_21.setTitle(_translate("MainWindowSett", "Zero Combine Setting", None))
        self.label_13.setText(_translate("MainWindowSett", "Combine", None))
        self.comboBox_2.setItemText(0, _translate("MainWindowSett", "median", None))
        self.comboBox_2.setItemText(1, _translate("MainWindowSett", "average", None))
        self.label_18.setText(_translate("MainWindowSett", "Reject", None))
        self.comboBox_3.setItemText(0, _translate("MainWindowSett", "none", None))
        self.comboBox_3.setItemText(1, _translate("MainWindowSett", "minmax", None))
        self.comboBox_3.setItemText(2, _translate("MainWindowSett", "ccdclip", None))
        self.comboBox_3.setItemText(3, _translate("MainWindowSett", "crreject", None))
        self.comboBox_3.setItemText(4, _translate("MainWindowSett", "sigclip", None))
        self.comboBox_3.setItemText(5, _translate("MainWindowSett", "avsigclip", None))
        self.comboBox_3.setItemText(6, _translate("MainWindowSett", "pclip", None))
        self.label_19.setText(_translate("MainWindowSett", "ccdtype", None))
        self.groupBox_22.setTitle(_translate("MainWindowSett", "Dark Combine Setting", None))
        self.label_29.setText(_translate("MainWindowSett", "Combine", None))
        self.comboBox_4.setItemText(0, _translate("MainWindowSett", "median", None))
        self.comboBox_4.setItemText(1, _translate("MainWindowSett", "average", None))
        self.label_30.setText(_translate("MainWindowSett", "Reject", None))
        self.comboBox_5.setItemText(0, _translate("MainWindowSett", "none", None))
        self.comboBox_5.setItemText(1, _translate("MainWindowSett", "minmax", None))
        self.comboBox_5.setItemText(2, _translate("MainWindowSett", "ccdclip", None))
        self.comboBox_5.setItemText(3, _translate("MainWindowSett", "crreject", None))
        self.comboBox_5.setItemText(4, _translate("MainWindowSett", "sigclip", None))
        self.comboBox_5.setItemText(5, _translate("MainWindowSett", "avsigclip", None))
        self.comboBox_5.setItemText(6, _translate("MainWindowSett", "pclip", None))
        self.label_35.setText(_translate("MainWindowSett", "Scale", None))
        self.comboBox_8.setItemText(0, _translate("MainWindowSett", "exposure", None))
        self.comboBox_8.setItemText(1, _translate("MainWindowSett", "none", None))
        self.comboBox_8.setItemText(2, _translate("MainWindowSett", "mode", None))
        self.comboBox_8.setItemText(3, _translate("MainWindowSett", "median", None))
        self.comboBox_8.setItemText(4, _translate("MainWindowSett", "mean", None))
        self.label_28.setText(_translate("MainWindowSett", "ccdtype", None))
        self.groupBox_23.setTitle(_translate("MainWindowSett", "Flat Combine Setting", None))
        self.label_32.setText(_translate("MainWindowSett", "Combine", None))
        self.comboBox_6.setItemText(0, _translate("MainWindowSett", "median", None))
        self.comboBox_6.setItemText(1, _translate("MainWindowSett", "average", None))
        self.label_33.setText(_translate("MainWindowSett", "Reject", None))
        self.comboBox_7.setItemText(0, _translate("MainWindowSett", "none", None))
        self.comboBox_7.setItemText(1, _translate("MainWindowSett", "minmax", None))
        self.comboBox_7.setItemText(2, _translate("MainWindowSett", "ccdclip", None))
        self.comboBox_7.setItemText(3, _translate("MainWindowSett", "crreject", None))
        self.comboBox_7.setItemText(4, _translate("MainWindowSett", "sigclip", None))
        self.comboBox_7.setItemText(5, _translate("MainWindowSett", "avsigclip", None))
        self.comboBox_7.setItemText(6, _translate("MainWindowSett", "pclip", None))
        self.label_36.setText(_translate("MainWindowSett", "Subset", None))
        self.comboBox_9.setItemText(0, _translate("MainWindowSett", "yes", None))
        self.comboBox_9.setItemText(1, _translate("MainWindowSett", "no", None))
        self.label_31.setText(_translate("MainWindowSett", "ccdtype", None))
        self.groupBox_24.setTitle(_translate("MainWindowSett", "Calibration Ssetting", None))
        self.label_37.setText(_translate("MainWindowSett", "Subset", None))
        self.comboBox_10.setItemText(0, _translate("MainWindowSett", "yes", None))
        self.comboBox_10.setItemText(1, _translate("MainWindowSett", "no", None))
        self.label_34.setText(_translate("MainWindowSett", "ccdtype", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindowSett", "Calibration", None))
        self.groupBox_14.setTitle(_translate("MainWindowSett", "FitSkyPars", None))
        self.label_40.setText(_translate("MainWindowSett", "Annulus", None))
        self.label_42.setText(_translate("MainWindowSett", "Dannulus", None))
        self.label_46.setText(_translate("MainWindowSett", "CBox", None))
        self.groupBox_13.setTitle(_translate("MainWindowSett", "DataPars", None))
        self.label_39.setText(_translate("MainWindowSett", "Filter", None))
        self.lineEdit_13.setText(_translate("MainWindowSett", "exptime", None))
        self.label_38.setText(_translate("MainWindowSett", "Exposur", None))
        self.lineEdit_14.setText(_translate("MainWindowSett", "subset", None))
        self.groupBox_15.setTitle(_translate("MainWindowSett", "PhotPars", None))
        self.label_44.setText(_translate("MainWindowSett", "Apertur", None))
        self.lineEdit_15.setText(_translate("MainWindowSett", "10,15,20,25,30", None))
        self.label_45.setText(_translate("MainWindowSett", "ZMag", None))
        self.lineEdit_16.setText(_translate("MainWindowSett", "25", None))
        self.label_57.setText(_translate("MainWindowSett", "Gain", None))
        self.lineEdit_26.setText(_translate("MainWindowSett", "gain", None))
        self.label_77.setText(_translate("MainWindowSett", "FixPix", None))
        self.groupBox_20.setTitle(_translate("MainWindowSett", "WCS", None))
        self.label_65.setText(_translate("MainWindowSett", "Right ascension", None))
        self.lineEdit_22.setText(_translate("MainWindowSett", "ra", None))
        self.label_66.setText(_translate("MainWindowSett", "Declination", None))
        self.lineEdit_23.setText(_translate("MainWindowSett", "dec", None))
        self.groupBox_17.setTitle(_translate("MainWindowSett", "Location and Time", None))
        self.label_48.setText(_translate("MainWindowSett", "Time OBS", None))
        self.label_47.setText(_translate("MainWindowSett", "Observatory", None))
        self.lineEdit_18.setText(_translate("MainWindowSett", "observat", None))
        self.lineEdit_17.setText(_translate("MainWindowSett", "time-obs", None))
        self.label_67.setText(_translate("MainWindowSett", "Date OBS", None))
        self.lineEdit_24.setText(_translate("MainWindowSett", "date-obs", None))
        self.checkBox_4.setText(_translate("MainWindowSett", "Epoch", None))
        self.checkBox_12.setText(_translate("MainWindowSett", "Time Stamp", None))
        self.groupBox_19.setTitle(_translate("MainWindowSett", "Star finder", None))
        self.label_64.setText(_translate("MainWindowSett", "Flux Radius", None))
        self.label_68.setText(_translate("MainWindowSett", "Min FWHM", None))
        self.label_69.setText(_translate("MainWindowSett", "Max FWHM", None))
        self.label_70.setText(_translate("MainWindowSett", "Maximum Stars To find", None))
        self.groupBox_31.setTitle(_translate("MainWindowSett", "Extract From Header", None))
        self.pushButton_50.setText(_translate("MainWindowSett", "<<", None))
        self.pushButton_49.setText(_translate("MainWindowSett", ">>", None))
        self.pushButton_51.setText(_translate("MainWindowSett", "Update List", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindowSett", "Photometry", None))
        self.checkBox_16.setText(_translate("MainWindowSett", "Additionally Create Mask Files", None))
        self.label_74.setText(_translate("MainWindowSett", "Gain", None))
        self.label_75.setText(_translate("MainWindowSett", "Read Noise", None))
        self.label_76.setText(_translate("MainWindowSett", "Sigma Clip", None))
        self.label_79.setText(_translate("MainWindowSett", "Sigma Frac.", None))
        self.label_78.setText(_translate("MainWindowSett", "Object Lim.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindowSett", "Cosmic Cleaner", None))
        self.label_72.setText(_translate("MainWindowSett", "Server", None))
        self.lineEdit_27.setText(_translate("MainWindowSett", "http://nova.astrometry.net/api/", None))
        self.label_73.setText(_translate("MainWindowSett", "Api Key", None))
        self.groupBox_36.setTitle(_translate("MainWindowSett", "Before Upload:", None))
        self.radioButton.setText(_translate("MainWindowSett", "Do Nothing", None))
        self.radioButton_2.setText(_translate("MainWindowSett", "Compress (For Low Band Widths)", None))
        self.radioButton_3.setText(_translate("MainWindowSett", "Convert to Binary File (For Very Low Band Widths)", None))
        self.checkBox_18.setText(_translate("MainWindowSett", "Align Befor Application", None))
        self.checkBox_19.setText(_translate("MainWindowSett", "Create WCS Headers Separately", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindowSett", "WCS", None))
        self.groupBox_3.setTitle(_translate("MainWindowSett", "Save", None))
        self.label_4.setText(_translate("MainWindowSett", "Session Name", None))
        self.pushButton_3.setText(_translate("MainWindowSett", "Save", None))
        self.groupBox_2.setTitle(_translate("MainWindowSett", "Load", None))
        self.label_3.setText(_translate("MainWindowSett", "Session Name", None))
        self.pushButton_2.setText(_translate("MainWindowSett", "Load", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindowSett", "Sessions", None))
        self.pushButton.setText(_translate("MainWindowSett", "Save", None))

