# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uisw/myraf.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(554, 327)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(554, 327))
        MainWindow.setMaximumSize(QtCore.QSize(554, 327))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(128, 128))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setAutoFillBackground(True)
        self.pushButton.setText(_fromUtf8(""))
        self.pushButton.setIconSize(QtCore.QSize(80, 80))
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(128, 128))
        self.pushButton_2.setMouseTracking(True)
        self.pushButton_2.setAutoFillBackground(True)
        self.pushButton_2.setText(_fromUtf8(""))
        self.pushButton_2.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(128, 128))
        self.pushButton_3.setMouseTracking(True)
        self.pushButton_3.setAutoFillBackground(True)
        self.pushButton_3.setText(_fromUtf8(""))
        self.pushButton_3.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(128, 128))
        self.pushButton_4.setMouseTracking(True)
        self.pushButton_4.setAutoFillBackground(True)
        self.pushButton_4.setText(_fromUtf8(""))
        self.pushButton_4.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 0, 3, 1, 2)
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(128, 128))
        self.pushButton_5.setMouseTracking(True)
        self.pushButton_5.setAutoFillBackground(True)
        self.pushButton_5.setText(_fromUtf8(""))
        self.pushButton_5.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(128, 128))
        self.pushButton_6.setMouseTracking(True)
        self.pushButton_6.setAutoFillBackground(True)
        self.pushButton_6.setText(_fromUtf8(""))
        self.pushButton_6.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout.addWidget(self.pushButton_6, 1, 1, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(128, 128))
        self.pushButton_7.setMouseTracking(True)
        self.pushButton_7.setAutoFillBackground(True)
        self.pushButton_7.setText(_fromUtf8(""))
        self.pushButton_7.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout.addWidget(self.pushButton_7, 1, 2, 1, 2)
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(128, 128))
        self.pushButton_8.setMouseTracking(True)
        self.pushButton_8.setAutoFillBackground(True)
        self.pushButton_8.setText(_fromUtf8(""))
        self.pushButton_8.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout.addWidget(self.pushButton_8, 1, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 554, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionCalibration = QtGui.QAction(MainWindow)
        self.actionCalibration.setObjectName(_fromUtf8("actionCalibration"))
        self.actionAlign = QtGui.QAction(MainWindow)
        self.actionAlign.setObjectName(_fromUtf8("actionAlign"))
        self.actionPhotometry = QtGui.QAction(MainWindow)
        self.actionPhotometry.setObjectName(_fromUtf8("actionPhotometry"))
        self.actionGraph = QtGui.QAction(MainWindow)
        self.actionGraph.setObjectName(_fromUtf8("actionGraph"))
        self.actionEditor = QtGui.QAction(MainWindow)
        self.actionEditor.setObjectName(_fromUtf8("actionEditor"))
        self.actionScheduler = QtGui.QAction(MainWindow)
        self.actionScheduler.setObjectName(_fromUtf8("actionScheduler"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.menuFile.addAction(self.actionQuit)
        self.menuWindow.addAction(self.actionCalibration)
        self.menuWindow.addAction(self.actionAlign)
        self.menuWindow.addAction(self.actionPhotometry)
        self.menuWindow.addAction(self.actionGraph)
        self.menuWindow.addAction(self.actionEditor)
        self.menuWindow.addAction(self.actionScheduler)
        self.menuWindow.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MYRaf3 Beta", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuWindow.setTitle(_translate("MainWindow", "Window", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionCalibration.setText(_translate("MainWindow", "Calibration", None))
        self.actionAlign.setText(_translate("MainWindow", "Align", None))
        self.actionPhotometry.setText(_translate("MainWindow", "Photometry", None))
        self.actionGraph.setText(_translate("MainWindow", "Graph", None))
        self.actionEditor.setText(_translate("MainWindow", "Editor", None))
        self.actionScheduler.setText(_translate("MainWindow", "Scheduler", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))

