# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uisw/scheduler.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindowSche(object):
    def setupUi(self, MainWindowSche):
        MainWindowSche.setObjectName(_fromUtf8("MainWindowSche"))
        MainWindowSche.resize(800, 784)
        self.centralwidget = QtGui.QWidget(MainWindowSche)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_12 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.groupBox_30 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_30.setObjectName(_fromUtf8("groupBox_30"))
        self.gridLayout_104 = QtGui.QGridLayout(self.groupBox_30)
        self.gridLayout_104.setObjectName(_fromUtf8("gridLayout_104"))
        self.graphicsView = QtGui.QGraphicsView(self.groupBox_30)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout_104.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_30, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.listView = QtGui.QListView(self.groupBox)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.gridLayout_8.addWidget(self.listView, 0, 0, 1, 4)
        spacerItem = QtGui.QSpacerItem(55, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButton_31 = QtGui.QPushButton(self.groupBox)
        self.pushButton_31.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_31.setMaximumSize(QtCore.QSize(100, 25))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../Downloads/.designer/.designer/backup/img/rem.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_31.setIcon(icon)
        self.pushButton_31.setObjectName(_fromUtf8("pushButton_31"))
        self.gridLayout_8.addWidget(self.pushButton_31, 1, 1, 1, 1)
        self.pushButton_48 = QtGui.QPushButton(self.groupBox)
        self.pushButton_48.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_48.setObjectName(_fromUtf8("pushButton_48"))
        self.gridLayout_8.addWidget(self.pushButton_48, 1, 2, 1, 1)
        self.pushButton_28 = QtGui.QPushButton(self.groupBox)
        self.pushButton_28.setMaximumSize(QtCore.QSize(100, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../Downloads/.designer/.designer/backup/img/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_28.setIcon(icon1)
        self.pushButton_28.setObjectName(_fromUtf8("pushButton_28"))
        self.gridLayout_8.addWidget(self.pushButton_28, 1, 3, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox, 1, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_10.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(180, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(180, 16777215))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_10.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.groupBox_25 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_25.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_25.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox_25.setObjectName(_fromUtf8("groupBox_25"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_25)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget_8 = QtGui.QTabWidget(self.groupBox_25)
        self.tabWidget_8.setEnabled(True)
        self.tabWidget_8.setDocumentMode(False)
        self.tabWidget_8.setTabsClosable(False)
        self.tabWidget_8.setMovable(False)
        self.tabWidget_8.setObjectName(_fromUtf8("tabWidget_8"))
        self.tab_26 = QtGui.QWidget()
        self.tab_26.setObjectName(_fromUtf8("tab_26"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_26)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.listWidget_13 = QtGui.QListWidget(self.tab_26)
        self.listWidget_13.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_13.setObjectName(_fromUtf8("listWidget_13"))
        self.gridLayout_2.addWidget(self.listWidget_13, 0, 0, 1, 2)
        self.pushButton_23 = QtGui.QPushButton(self.tab_26)
        self.pushButton_23.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_23.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_23.setIcon(icon)
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.gridLayout_2.addWidget(self.pushButton_23, 1, 0, 1, 1)
        self.pushButton_20 = QtGui.QPushButton(self.tab_26)
        self.pushButton_20.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_20.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_20.setIcon(icon1)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.gridLayout_2.addWidget(self.pushButton_20, 1, 1, 1, 1)
        self.tabWidget_8.addTab(self.tab_26, _fromUtf8(""))
        self.tab_27 = QtGui.QWidget()
        self.tab_27.setObjectName(_fromUtf8("tab_27"))
        self.gridLayout = QtGui.QGridLayout(self.tab_27)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.listWidget_14 = QtGui.QListWidget(self.tab_27)
        self.listWidget_14.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_14.setObjectName(_fromUtf8("listWidget_14"))
        self.gridLayout.addWidget(self.listWidget_14, 0, 0, 1, 2)
        self.pushButton_24 = QtGui.QPushButton(self.tab_27)
        self.pushButton_24.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_24.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_24.setIcon(icon)
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.gridLayout.addWidget(self.pushButton_24, 1, 0, 1, 1)
        self.pushButton_21 = QtGui.QPushButton(self.tab_27)
        self.pushButton_21.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_21.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_21.setIcon(icon1)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.gridLayout.addWidget(self.pushButton_21, 1, 1, 1, 1)
        self.tabWidget_8.addTab(self.tab_27, _fromUtf8(""))
        self.tab_28 = QtGui.QWidget()
        self.tab_28.setObjectName(_fromUtf8("tab_28"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_28)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.listWidget_15 = QtGui.QListWidget(self.tab_28)
        self.listWidget_15.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_15.setObjectName(_fromUtf8("listWidget_15"))
        self.gridLayout_4.addWidget(self.listWidget_15, 0, 0, 1, 2)
        self.pushButton_25 = QtGui.QPushButton(self.tab_28)
        self.pushButton_25.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_25.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_25.setIcon(icon)
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.gridLayout_4.addWidget(self.pushButton_25, 1, 0, 1, 1)
        self.pushButton_22 = QtGui.QPushButton(self.tab_28)
        self.pushButton_22.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_22.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_22.setIcon(icon1)
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.gridLayout_4.addWidget(self.pushButton_22, 1, 1, 1, 1)
        self.tabWidget_8.addTab(self.tab_28, _fromUtf8(""))
        self.tab_29 = QtGui.QWidget()
        self.tab_29.setObjectName(_fromUtf8("tab_29"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_29)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.listWidget_16 = QtGui.QListWidget(self.tab_29)
        self.listWidget_16.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_16.setObjectName(_fromUtf8("listWidget_16"))
        self.gridLayout_5.addWidget(self.listWidget_16, 0, 0, 1, 2)
        self.pushButton_27 = QtGui.QPushButton(self.tab_29)
        self.pushButton_27.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_27.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_27.setIcon(icon)
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.gridLayout_5.addWidget(self.pushButton_27, 1, 0, 1, 1)
        self.pushButton_26 = QtGui.QPushButton(self.tab_29)
        self.pushButton_26.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_26.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_26.setIcon(icon1)
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.gridLayout_5.addWidget(self.pushButton_26, 1, 1, 1, 1)
        self.tabWidget_8.addTab(self.tab_29, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget_8, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_25, 1, 0, 1, 2)
        self.groupBox_27 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_27.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_27.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox_27.setObjectName(_fromUtf8("groupBox_27"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_27)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.checkBox_11 = QtGui.QCheckBox(self.groupBox_27)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.gridLayout_6.addWidget(self.checkBox_11, 0, 0, 1, 1)
        self.groupBox_29 = QtGui.QGroupBox(self.groupBox_27)
        self.groupBox_29.setEnabled(True)
        self.groupBox_29.setCheckable(False)
        self.groupBox_29.setChecked(False)
        self.groupBox_29.setObjectName(_fromUtf8("groupBox_29"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_29)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.listWidget_17 = QtGui.QListWidget(self.groupBox_29)
        self.listWidget_17.setEnabled(True)
        self.listWidget_17.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_17.setObjectName(_fromUtf8("listWidget_17"))
        self.gridLayout_7.addWidget(self.listWidget_17, 2, 0, 1, 2)
        self.pushButton_47 = QtGui.QPushButton(self.groupBox_29)
        self.pushButton_47.setEnabled(True)
        self.pushButton_47.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_47.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_47.setIcon(icon)
        self.pushButton_47.setObjectName(_fromUtf8("pushButton_47"))
        self.gridLayout_7.addWidget(self.pushButton_47, 3, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(89, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 3, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBox_29)
        self.checkBox.setEnabled(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_7.addWidget(self.checkBox, 1, 0, 1, 2)
        self.gridLayout_6.addWidget(self.groupBox_29, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_27, 2, 0, 1, 2)
        self.gridLayout_12.addLayout(self.gridLayout_10, 0, 1, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_9.addWidget(self.progressBar, 0, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_9.addWidget(self.pushButton, 0, 1, 2, 1)
        self.progressBar_2 = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.gridLayout_9.addWidget(self.progressBar_2, 1, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_9, 1, 0, 1, 2)
        MainWindowSche.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindowSche)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindowSche.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindowSche)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindowSche.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowSche)
        self.tabWidget_8.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindowSche)

    def retranslateUi(self, MainWindowSche):
        MainWindowSche.setWindowTitle(_translate("MainWindowSche", "MYRaf3 - Scheduler", None))
        self.groupBox_30.setTitle(_translate("MainWindowSche", "Display:", None))
        self.groupBox.setTitle(_translate("MainWindowSche", "Scheduler List", None))
        self.pushButton_31.setText(_translate("MainWindowSche", "Remove", None))
        self.pushButton_48.setText(_translate("MainWindowSche", "Update", None))
        self.pushButton_28.setText(_translate("MainWindowSche", "Add", None))
        self.label.setText(_translate("MainWindowSche", "Session", None))
        self.groupBox_25.setTitle(_translate("MainWindowSche", "Images:", None))
        self.pushButton_23.setText(_translate("MainWindowSche", "Remove", None))
        self.pushButton_20.setText(_translate("MainWindowSche", "Add", None))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.tab_26), _translate("MainWindowSche", "Images", None))
        self.pushButton_24.setText(_translate("MainWindowSche", "Remove", None))
        self.pushButton_21.setText(_translate("MainWindowSche", "Add", None))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.tab_27), _translate("MainWindowSche", "Bias", None))
        self.pushButton_25.setText(_translate("MainWindowSche", "Remove", None))
        self.pushButton_22.setText(_translate("MainWindowSche", "Add", None))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.tab_28), _translate("MainWindowSche", "Dark", None))
        self.pushButton_27.setText(_translate("MainWindowSche", "Remove", None))
        self.pushButton_26.setText(_translate("MainWindowSche", "Add", None))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.tab_29), _translate("MainWindowSche", "Flat", None))
        self.groupBox_27.setTitle(_translate("MainWindowSche", "Processes:", None))
        self.checkBox_11.setText(_translate("MainWindowSche", "Align", None))
        self.groupBox_29.setTitle(_translate("MainWindowSche", "Photometry", None))
        self.pushButton_47.setText(_translate("MainWindowSche", "Remove", None))
        self.checkBox.setText(_translate("MainWindowSche", "Ensemble", None))
        self.pushButton.setText(_translate("MainWindowSche", ":go", None))

